baseurl = "/"
languageCode = "en-us"
title = "Tasty Licks"

[params]
  description = "An example website for restaurants built by [@eliwilliamson](https://github.com/eliwilliamson) using [Victor Hugo](https://github.com/netlify/victor-hugo)."

[[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 1
[[menu.main]
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 2
