backend:
  name: github
  repo: bdougie/hugo-restaurant-template
  branch: master

media_folder: "src/img/gallery" # Folder where user uploaded files should go
public_folder: "img/gallery"

collections:
  - name: food
    label: "Food Item" # Used in the UI, ie.: "New Post"
    folder: "site/content/food" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name of Item", name: "title", widget: "string"}
      - {label: "Supported Meals", name: "categories", widget: "list", default: ["lunch", "dinner"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of Food", name: "type", widget: "string", default: "raw bar"}
      - {label: "Price", name: "price", widget: "string"}
  - name: drinks
    label: "Drink Item" # Used in the UI, ie.: "New Post"
    folder: "site/content/drinks" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name of Drink", name: "title", widget: "string"}
      - {label: "Drink Marker", name: "categories", widget: "hidden", default: ["drinks"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of Drink", name: "type", widget: "string", default: "beer"}
      - {label: "Price", name: "price", widget: "string"}
  - name: gallery
    label: "Gallery Image" # Used in the UI, ie.: "New Post"
    folder: "site/content/gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Gallery Image", name: "image", widget: "image"}
